name: etl-run
on:
  schedule:
    - cron: "15 18 * * 1-5"

jobs:
  data_pipeline:
    runs-on: ubuntu-latest
    name: Run Daily ETL Process from Monday - Friday
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r etl_requirements.txt
      - name: Run ETL.py
        env: # Read Secrets as environment variables
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          HERTS_COVID_URL: ${{ secrets.HERTS_COVID_URL }}
          ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
        run: python ./scripts/etl.py
