name: etl-run
on:
  schedule:
    - cron: "* * * * *"
    # - cron: "15 17 * * 1-5"
jobs:
  build:
    runs-on: ubuntu-latest
    name: Run Daily ETL Process from Monday - Friday
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run ETL.py
        env: # Read Secrets as environment variables
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          HERTS_COVID_URL: ${{ secrets.HERTS_COVID_URL }}
          DEVELOPMENT: ${{ secrets.DEVELOPMENT }}
        run: python etl.py
